# Generated by Django 5.2.15 on 2026-07-08 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='항목 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='항목 이름')),
            ],
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='플랜 종류 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='항목 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='항목 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='플랜명 (ex: Basic Channel Operation)')),
                ('subname', models.CharField(blank=True, max_length=255, null=True, verbose_name='서브명 (ex: 베이직 채널 운영)')),
                ('price', models.IntegerField(verbose_name='가격(만원)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, to='product.item', verbose_name='제작 항목')),
                ('operations', models.ManyToManyField(blank=True, to='product.operation', verbose_name='운영 목적')),
                ('plan_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.plantype', verbose_name='플랜 종류')),
                ('productions', models.ManyToManyField(blank=True, to='product.production', verbose_name='촬영 / 편수')),
                ('recommends', models.ManyToManyField(blank=True, to='product.recommend', verbose_name='추천 대상')),
            ],
        ),
    ]
