# Generated by Django 5.2.4 on 2026-07-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='구독 상품명')),
                ('description', models.TextField(verbose_name='상품 설명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('is_active', models.BooleanField(default=True, verbose_name='개별 판매 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
