# Generated by Django 5.2.4 on 2026-07-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userinfo_production'),
        ('product', '0002_item_operation_plan_production_recommend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='plan',
            name='items',
            field=models.ManyToManyField(blank=True, to='product.item', verbose_name='제작 항목'),
        ),
        migrations.AddField(
            model_name='plan',
            name='operations',
            field=models.ManyToManyField(blank=True, to='product.operation', verbose_name='운영 목적'),
        ),
        migrations.AddField(
            model_name='plan',
            name='productions',
            field=models.ManyToManyField(blank=True, to='product.production', verbose_name='촬영 / 편수'),
        ),
        migrations.AddField(
            model_name='plan',
            name='recommends',
            field=models.ManyToManyField(blank=True, to='product.recommend', verbose_name='추천 대상'),
        ),
    ]
