# Generated by Django 5.2.15 on 2026-07-07 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delete_product_plan_items_plan_operations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='플랜 종류 이름')),
            ],
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.plantype', verbose_name='플랜 종류'),
        ),
    ]
