# Generated by Django 5.2.4 on 2026-07-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_kr', models.CharField(blank=True, max_length=255, null=True, verbose_name='로고 (KR)')),
                ('logo_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='로고 (EN)')),
            ],
            options={
                'verbose_name': '사이트 설정',
                'verbose_name_plural': '사이트 설정',
            },
        ),
    ]
