# Generated by Django 5.2.15 on 2026-07-08 09:39

import system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_kr', models.CharField(blank=True, default='국문 로고', max_length=255, null=True, verbose_name='국문 로고 텍스트/경로')),
                ('logo_en', models.CharField(blank=True, default='EN_LOGO', max_length=255, null=True, verbose_name='영문 로고 텍스트/경로')),
                ('about_headings', models.JSONField(blank=True, default=system.models.default_about_headings, null=True, verbose_name='About 섹션 제목 리스트')),
                ('email', models.EmailField(blank=True, default='email@gmail.com', max_length=254, null=True, verbose_name='스튜디오 이메일')),
                ('phone', models.CharField(blank=True, default='+82 10-0000-0000', max_length=50, null=True, verbose_name='스튜디오 전화번호')),
                ('address', models.CharField(blank=True, default='우리집', max_length=255, null=True, verbose_name='스튜디오 주소')),
                ('instagram_handle', models.CharField(blank=True, default='인스타핸들', max_length=100, null=True, verbose_name='인스타그램 핸들')),
                ('instagram_url', models.URLField(blank=True, default='https://www.naver.com/', max_length=255, null=True, verbose_name='인스타그램 주소')),
                ('is_service_visible', models.BooleanField(default=True, verbose_name='Service 노출 여부')),
                ('service_title', models.CharField(blank=True, default='MONTHLY PLAN', max_length=255, null=True, verbose_name='Service 타이틀')),
                ('service_desc', models.CharField(blank=True, default='영상 운영 가격 / 한달 기준', max_length=255, null=True, verbose_name='Service 서브설명')),
                ('is_about_visible', models.BooleanField(default=True, verbose_name='About 노출 여부')),
                ('about_title', models.CharField(blank=True, default='ABOUT THE STUDIO', max_length=255, null=True, verbose_name='About 타이틀')),
                ('about_desc', models.CharField(blank=True, default='하이어, 더 높은 곳으로', max_length=255, null=True, verbose_name='About 서브설명')),
                ('is_contact_visible', models.BooleanField(default=True, verbose_name='Contact 노출 여부')),
                ('contact_title', models.CharField(blank=True, default="LET'S GO HIGHER", max_length=255, null=True, verbose_name='Contact 페이지 타이틀')),
                ('contact_header_title', models.CharField(blank=True, default='GET IN TOUCH', max_length=255, null=True, verbose_name='Footer(Contact) 타이틀')),
                ('contact_header_desc', models.CharField(blank=True, default='하이어, 더 높은 곳으로', max_length=255, null=True, verbose_name='Footer(Contact) 서브설명')),
                ('footer_slogan_main', models.JSONField(blank=True, default=system.models.default_footer_slogan_main, null=True, verbose_name='푸터 메인 슬로건')),
                ('footer_slogan_sub', models.CharField(blank=True, default="Let's go higher.", max_length=255, null=True, verbose_name='푸터 서브 슬로건')),
            ],
            options={
                'verbose_name': '사이트 설정',
                'verbose_name_plural': '사이트 설정',
            },
        ),
    ]
