# Generated by Django 5.2.4 on 2026-07-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_heading_1',
            field=models.CharField(blank=True, default='브랜드의 고도를 높이는', max_length=255, null=True, verbose_name='About 제목 1'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_heading_2',
            field=models.CharField(blank=True, default='우상향 프로덕션', max_length=255, null=True, verbose_name='About 제목 2'),
        ),
    ]
