# Generated by Django 5.2.4 on 2026-07-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_sitesetting_about_heading_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='about_heading_1',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='about_heading_2',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_headings',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='About 섹션 제목들'),
        ),
    ]
