# Generated by Django 5.2.4 on 2026-07-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_remove_sitesetting_about_heading_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(blank=True, default='경기도 의정부시, KR', max_length=255, null=True, verbose_name='스튜디오 주소'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(blank=True, default='higher3pd@gmail.com', max_length=255, null=True, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram_handle',
            field=models.CharField(blank=True, default='@higher.production', max_length=100, null=True, verbose_name='인스타그램 핸들'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com/higher.production', max_length=255, null=True, verbose_name='인스타그램 주소'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(blank=True, default='+82 10-3313-0388', max_length=50, null=True, verbose_name='전화번호'),
        ),
    ]
