# Generated by Django 5.2.4 on 2026-07-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_sitesetting_address_sitesetting_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='contact_title',
            field=models.CharField(blank=True, default="LET'S GO HIGHER", max_length=255, null=True, verbose_name='Contact 페이지 타이틀'),
        ),
    ]
