# Generated by Django 5.2.4 on 2026-07-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_sitesetting_contact_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='footer_slogan_main',
            field=models.TextField(blank=True, default='당신의 브랜드,\n한 단계 더 위로', null=True, verbose_name='푸터 메인 슬로건'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_slogan_sub',
            field=models.CharField(blank=True, default="Let's go higher.", max_length=255, null=True, verbose_name='푸터 서브 슬로건'),
        ),
    ]
