# Generated by Django 5.2.4 on 2026-07-06 23:48

import system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_sitesetting_footer_slogan_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_slogan_main',
            field=models.JSONField(blank=True, default=system.models.default_footer_slogan_main, null=True, verbose_name='푸터 메인 슬로건'),
        ),
    ]
