# Generated by Django 5.2.4 on 2026-07-07 00:03

import system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_sitesetting_footer_slogan_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_desc',
            field=models.CharField(blank=True, default='하이어, 더 높은 곳으로', max_length=255, null=True, verbose_name='About 서브설명'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_title',
            field=models.CharField(blank=True, default='ABOUT THE STUDIO', max_length=255, null=True, verbose_name='About 타이틀'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_header_desc',
            field=models.CharField(blank=True, default='하이어, 더 높은 곳으로', max_length=255, null=True, verbose_name='Footer(Contact) 서브설명'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_header_title',
            field=models.CharField(blank=True, default='GET IN TOUCH', max_length=255, null=True, verbose_name='Footer(Contact) 타이틀'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='is_about_visible',
            field=models.BooleanField(default=True, verbose_name='About 노출 여부'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='is_contact_visible',
            field=models.BooleanField(default=True, verbose_name='Contact 노출 여부'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='is_service_visible',
            field=models.BooleanField(default=True, verbose_name='Service 노출 여부'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='service_desc',
            field=models.CharField(blank=True, default='영상 운영 가격 / 한달 기준', max_length=255, null=True, verbose_name='Service 서브설명'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='service_title',
            field=models.CharField(blank=True, default='MONTHLY PLAN', max_length=255, null=True, verbose_name='Service 타이틀'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='about_headings',
            field=models.JSONField(blank=True, default=system.models.default_about_headings, null=True, verbose_name='About 섹션 제목 리스트'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(blank=True, default='higher3pd@gmail.com', max_length=254, null=True, verbose_name='스튜디오 이메일'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo_en',
            field=models.CharField(blank=True, default='HIGHER PRODUCTION', max_length=255, null=True, verbose_name='영문 로고 텍스트/경로'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo_kr',
            field=models.CharField(blank=True, default='하이어 프로덕션', max_length=255, null=True, verbose_name='국문 로고 텍스트/경로'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(blank=True, default='+82 10-3313-0388', max_length=50, null=True, verbose_name='스튜디오 전화번호'),
        ),
    ]
