# Generated by Django 5.2.15 on 2026-07-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_sitesetting_about_desc_sitesetting_about_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(blank=True, default='우리집', max_length=255, null=True, verbose_name='스튜디오 주소'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(blank=True, default='email@gmail.com', max_length=254, null=True, verbose_name='스튜디오 이메일'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram_handle',
            field=models.CharField(blank=True, default='인스타핸들', max_length=100, null=True, verbose_name='인스타그램 핸들'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://인스타_주소', max_length=255, null=True, verbose_name='인스타그램 주소'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo_en',
            field=models.CharField(blank=True, default='EN_LOGO', max_length=255, null=True, verbose_name='영문 로고 텍스트/경로'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo_kr',
            field=models.CharField(blank=True, default='국문 로고', max_length=255, null=True, verbose_name='국문 로고 텍스트/경로'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(blank=True, default='+82 10-0000-0000', max_length=50, null=True, verbose_name='스튜디오 전화번호'),
        ),
    ]
