# Generated by Django 5.2.4 on 2026-07-05 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='작품명')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='영상 링크')),
                ('content', models.TextField(blank=True, null=True, verbose_name='게시글 내용')),
                ('status', models.CharField(choices=[('IN_PROGRESS', '작업중'), ('COMPLETED', '완료됨')], default='IN_PROGRESS', max_length=20, verbose_name='진행 상태')),
                ('is_visible', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to=settings.AUTH_USER_MODEL, verbose_name='관련 고객')),
            ],
        ),
    ]
