# Generated by Django 5.2.15 on 2026-07-08 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='브랜드명')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='부가설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='카테고리 소제목')),
                ('order', models.IntegerField(default=0, verbose_name='노출 순서(낮을수록 먼저 보임)')),
                ('is_vertical', models.BooleanField(default=False, verbose_name='세로형(쇼츠) 여부')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('name', models.CharField(max_length=100, verbose_name='성함')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='회사명')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='카테고리')),
                ('budget', models.CharField(blank=True, max_length=100, null=True, verbose_name='예산')),
                ('details', models.TextField(blank=True, null=True, verbose_name='상세 요청사항')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('is_read', models.BooleanField(default=False, verbose_name='확인 여부')),
                ('status', models.CharField(choices=[('UNPROCESSED', '미접수'), ('IN_PROGRESS', '처리 중'), ('COMPLETED', '처리 완료')], default='UNPROCESSED', max_length=20, verbose_name='처리 상태')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='프로젝트명')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='부가설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='work.brandclient', verbose_name='브랜드 클라이언트')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='작품명')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='영상 링크')),
                ('content', models.TextField(blank=True, null=True, verbose_name='게시글 내용')),
                ('status', models.CharField(choices=[('IN_PROGRESS', '작업중'), ('COMPLETED', '완료됨')], default='IN_PROGRESS', max_length=20, verbose_name='진행 상태')),
                ('is_visible', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='work.category', verbose_name='카테고리')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to=settings.AUTH_USER_MODEL, verbose_name='관련 고객')),
            ],
        ),
    ]
