# Generated by Django 5.2.4 on 2026-07-05 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('order', models.IntegerField(default=0, verbose_name='노출 순서(낮을수록 먼저 보임)')),
                ('is_vertical', models.BooleanField(default=False, verbose_name='세로형(쇼츠) 여부')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='work.category', verbose_name='카테고리'),
        ),
    ]
