# Generated by Django 5.2.15 on 2026-07-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('work', '0002_inquiry_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='plan',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='plans',
            field=models.ManyToManyField(blank=True, related_name='inquiries', to='product.plan', verbose_name='문의 플랜(다중선택)'),
        ),
    ]
