# Generated by Django 5.2.4 on 2026-07-05 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_category_work_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='브랜드명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='프로젝트명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='work.brandclient', verbose_name='브랜드 클라이언트')),
            ],
        ),
    ]
