# Generated by Django 5.2.4 on 2026-07-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_brandclient_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='카테고리 소제목'),
        ),
    ]
