# Generated by Django 5.2.15 on 2026-07-08 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_remove_inquiry_plan_inquiry_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='대분류명')),
                ('order', models.IntegerField(default=0, verbose_name='노출 순서(낮을수록 먼저 보임)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='work',
            name='category',
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='중분류명(채널명)')),
                ('order', models.IntegerField(default=0, verbose_name='노출 순서(낮을수록 먼저 보임)')),
                ('is_vertical', models.BooleanField(default=False, verbose_name='세로형(쇼츠) 여부')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='work.maincategory', verbose_name='대분류')),
            ],
            options={
                'ordering': ['main_category__order', 'order'],
            },
        ),
        migrations.AddField(
            model_name='work',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='work.subcategory', verbose_name='중분류'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
