# Generated by Django 5.2.4 on 2026-07-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_category_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandclient',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='부가설명'),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='부가설명'),
        ),
    ]
