# Generated by Django 5.2.15 on 2026-07-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_maincategory_remove_work_category_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_instagram',
            field=models.BooleanField(default=False, verbose_name='인스타그램 여부'),
        ),
        migrations.AddField(
            model_name='work',
            name='instagram_embed',
            field=models.TextField(blank=True, null=True, verbose_name='인스타그램 퍼가기 코드'),
        ),
    ]
