# Generated by Django 5.2.4 on 2026-07-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_brandclient_subtitle_project_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('name', models.CharField(max_length=100, verbose_name='성함')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='회사명')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='카테고리')),
                ('budget', models.CharField(blank=True, max_length=100, null=True, verbose_name='예산')),
                ('details', models.TextField(blank=True, null=True, verbose_name='상세 요청사항')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('is_read', models.BooleanField(default=False, verbose_name='확인 여부')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
