# Generated by Django 5.2.4 on 2026-07-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('UNPROCESSED', '미접수'), ('IN_PROGRESS', '처리 중'), ('COMPLETED', '처리 완료')], default='UNPROCESSED', max_length=20, verbose_name='처리 상태'),
        ),
    ]
