# Generated by Django 5.2.4 on 2026-07-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='회사 주소'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='회사명'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='담당자명'),
        ),
    ]
