# Generated by Django 5.2.4 on 2026-07-05 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo_company_address_userinfo_company_name_and_more'),
        ('product', '0002_item_operation_plan_production_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.plan'),
        ),
    ]
